version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  frontend:
    env_file: .env
    build: ./frontend/
    volumes:
      - static:/frontend_static

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static:/backend_static
    depends_on:
      - db

  gateway:
    build: ./gateway/
    env_file: .env
    volumes:
      - static:/staticfiles
    ports:
<<<<<<< HEAD
      - 9001:80
=======
      - 8000:80
    depends_on:
      - backend
      - frontend
      - db
>>>>>>> a432013f1a3998572d31f4d5a32d969e64db37c1
